"""Add tactical fields JSONB

Revision ID: 6bf7656c5532
Revises: 
Create Date: 2026-02-04 02:24:23.489265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6bf7656c5532'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. Agregamos las nuevas columnas tácticas
    op.add_column('matches', sa.Column('injuries', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('matches', sa.Column('lineups', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('matches', sa.Column('api_prediction', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    
    # 2. CORRECCIÓN AQUÍ: Agregamos server_default para rellenar datos existentes
    op.add_column('matches', sa.Column('created_at', sa.DateTime(), server_default=sa.func.now(), nullable=False))
    op.add_column('matches', sa.Column('updated_at', sa.DateTime(), server_default=sa.func.now(), nullable=False))
    
    # 3. Ajustamos columnas existentes a nullable=True (porque en tus datos viejos quizás no tenías estos IDs)
    op.alter_column('matches', 'season_year',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('matches', 'home_team_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('matches', 'away_team_id',
               existing_type=sa.INTEGER(),
               nullable=True)
               
    # 4. Convertimos JSON normal a JSONB (Más rápido)
    op.alter_column('matches', 'odds_data',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('matches', 'ai_analysis',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('matches', 'accuracy_log',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
               
    # 5. Eliminamos la columna vieja
    op.drop_column('matches', 'pro_data')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('pro_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.alter_column('matches', 'accuracy_log',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('matches', 'ai_analysis',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('matches', 'odds_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('matches', 'away_team_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('matches', 'home_team_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('matches', 'season_year',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('matches', 'updated_at')
    op.drop_column('matches', 'created_at')
    op.drop_column('matches', 'api_prediction')
    op.drop_column('matches', 'lineups')
    op.drop_column('matches', 'injuries')
    # ### end Alembic commands ###