"""add match statistics and auto_analyzed columns

Revision ID: ecd014c02a10
Revises: e1656291fe3b
Create Date: 2026-06-19 00:59:33.556883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ecd014c02a10'
down_revision: Union[str, None] = 'e1656291fe3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('statistics', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('matches', sa.Column('auto_analyzed', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matches', 'auto_analyzed')
    op.drop_column('matches', 'statistics')
    # ### end Alembic commands ###
